library(shinydashboard)
library(markdown)

# ==============================================================================
# Define header
# ==============================================================================
header <- dashboardHeader(title = "Effects of p-Hacking")

# ==============================================================================
# Define sidebar
# ==============================================================================
sidebar <- dashboardSidebar(
  sidebarMenu(
    id = "strategies",
    menuItem("Start Page", tabName = "startpage",
             icon = icon("certificate",lib = "glyphicon")),
    HTML("<p> <strong> <center> p-Hacking Strategies </strong> </center>"),
    menuItem("Composite Scores", tabName = "compositeScores",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Exploit Covariates", tabName = "exploitCovariates",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Exploit Cut-Offs", tabName = "exploitCutoffs",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Favorable Imputation", tabName = "favorableImputation",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Incorrect Rounding", tabName = "incorrectRounding",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Optional Stopping", tabName = "optionalStopping",
              icon = icon("stats",lib = "glyphicon")),
    menuItem("Outlier Exclusion", tabName = "outlierExclusion",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Selecting Effects", tabName = "selectEffects",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Selective Reporting DV", tabName = "selectiveReportingDV",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Selective Reporting IV", tabName = "selectiveReportingIV",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Exploiting Stat. Analysis", tabName = "statAnalysis",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Subgroup Analysis", tabName = "subgroupAnalysis",
             icon = icon("stats",lib = "glyphicon")),
    menuItem("Variable Transformation", tabName = "variableTransformation",
             icon = icon("stats",lib = "glyphicon"))
  )
)

# ==============================================================================
# Define body
# ==============================================================================

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "startpage",
            fluidRow(box(width=12, status = "primary",
                         includeMarkdown("mddoc/landingPage.md")))),
    # ------------------- Composite Scores -------------------------------------
    tabItem(tabName = "compositeScores",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/01_CompScores.md")
                         )),
            fluidRow(column(width=8,
                            fixedRow(box(width = 6, status = "primary",
                                         plotOutput("compScoresPlot1")),
                                     box(width = 6, status = "primary",
                                         plotOutput("compScoresPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("compScoresPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("compScoresFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("compScoresFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("compScoresPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("compScoresPlot5")))),
                     column(width=4,
                            box(width=12, status = "primary", height=750, background = "navy",
                                h4("Simulation settings"),
                                numericInput("nobsCompScores", label = "Number of observations", value = 30, min = 10, max = 1000),
                                numericInput("ncompvCompScores", label = "Number of items in composite score", value = 5, min = 3, max = 20),
                                uiOutput("uindeleteCompScores"),
                                sliderInput("rcompCompScores", label = "Correlation between composite score items", min = 0, max = 0.99, value = 0.8, step = 0.01),
                                radioButtons("strategyCompScores", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaCompScores", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterCompScores", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcCompScores", "Start simulation"))))),

    # ------------------- Exploit Covariates -----------------------------------
    tabItem(tabName = "exploitCovariates",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/02_ExploitCovariates.md")
                         )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("expCovPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("expCovPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("expCovPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("expCovFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("expCovFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("expCovPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("expCovPlot5")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsExpCov", label = "Number of observations per group", value = 30, min = 10, max = 1000),
                                numericInput("ncovExpCov", label = "Number of covariates", value = 3, min = 1, max = 10),
                                sliderInput("rcovExpCov", label = "Correlation between covariates", value = 0.3, min = 0, max = 0.99, step = 0.01),
                                sliderInput("rcovdvExpCov", label = "Correlation between covariates and dependent variable", value = 0.5, min = 0, max = 0.99, step = 0.01),
                                radioButtons("interactExpCov", label = "Should models include interactions?", choiceNames = list("No", "Yes"), choiceValues = list("No", "Yes")),
                                radioButtons("strategyExpCov", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaExpCov", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterExpCov", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcExpCov", "Start simulation"))))),

    # ------------------- Exploit Cutoffs --------------------------------------
    tabItem(tabName = "exploitCutoffs",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/03_ExploitCutoffs.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("expCutPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("expCutPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("expCutPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("expCutFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("expCutFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("expCutPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("expCutPlot5")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsExpCut", label = "Number of observations", value = 30, min = 10, max = 1000),
                                radioButtons("strategyExpCut", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaExpCut", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterExpCut", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcExpCut", "Start simulation"))))),

    # ------------------- Favorable Imputation ---------------------------------
    tabItem(tabName = "favorableImputation",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/04_FavorableImputation.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("favImpPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("favImpPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("favImpPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("favImpFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("favImpFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("favImpPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("favImpPlot5")))),
                     column(width=4,
                            box(width=12, status="primary", height=810, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsfavImp", label = "Number of observations", value = 30, min = 10, max = 1000),
                                sliderInput("missingfavImp", label = "Percentage of missing values", value = 0.1, min = 0, max = 0.5, step = 0.01),
                                checkboxGroupInput("whichImpfavImp", label = "Imputation methods", choiceNames = list("Delete missing values", "Mean imputation", "Median imputation", "Mode imputation", "Predictive mean matching", "Weighted predictive mean matching", "Sample from observed values", "Bayesian linear regression", "Linear regression ignoring model error", "Linear regression predicted values"),
                                                   choiceValues = as.list(as.character(c(1:10))), selected = as.character(c(1:3))),
                                radioButtons("strategyfavImp", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphafavImp", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterfavImp", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcfavImp", "Start simulation"))))),

    # ------------------- Incorrect Rounding -----------------------------------
    tabItem(tabName = "incorrectRounding",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/05_IncorrectRounding.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("roundingPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("roundingPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("roundingPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("roundingFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("roundingFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("roundingPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("roundingPlot5")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("levelRounding", label = "Rounding margin (e.g., 0.001 if all p-values smaller than 0.051 should be rounded to 0.05)", value = 0.001, min = 0.0001, max = 0.01),
                                radioButtons("altRounding", label = "Direction of the test", choiceNames = list("Two-sided", "One-sided (greater)"), choiceValues = list("two.sided", "greater")),
                                numericInput("alphaRounding", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterRounding", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcRounding", "Start simulation"))))),

    # ------------------- Optional Stopping ------------------------------------
    tabItem(tabName = "optionalStopping",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/06_OptionalStopping.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("optStopPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("optStopPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("optStopPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("optStopFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("optStopFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("optStopPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("optStopPlot5"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("optStopPlot6")),
                                     box(width=6, status = "primary",
                                         plotOutput("optStopPlot7")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nminOptStop", label = "Minimum sample size", value = 10, min = 5, max = 100),
                                numericInput("nmaxOptStop", label = "Maximum sample size", value = 100, min = 30, max = 500),
                                sliderInput("stepOptStop", label = "Step size", value = 1, min = 1, max = 10, step = 1),
                                radioButtons("altOptStop", label = "Direction of the test", choiceNames = list("Two-sided", "One-sided (greater)"), choiceValues = list("two.sided", "greater")),
                                numericInput("alphaOptStop", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterOptStop", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcOptStop", "Start simulation"))))),
    # ------------------- Outlier Exclusion ------------------------------------
    tabItem(tabName = "outlierExclusion",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/07_OutlierExclusion.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("outExclPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("outExclPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("outExclPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("outExclFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("outExclFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("outExclPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("outExclPlot5")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsOutExcl", label = "Number of observations", value = 30, min = 10, max = 1000),
                                checkboxGroupInput("whichOutExcl", label = "Outlier exclusion methods", choiceNames = list("Boxplot", "Stem & leaf plot", "Standard deviation", "Percentile", "Studentized residuals", "Standardized residuals", "DFBETA", "DFFITS", "Cook's D", "Mahalanobis distance", "Leverage values", "Covariance ratio"),
                                                   choiceValues = as.list(as.character(c(1:12))), selected = as.character(c(1:2))),
                                radioButtons("strategyOutExcl", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaOutExcl", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterOutExcl", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcOutExcl", "Start simulation"))))),

    # ------------------- Selective Reporting of Effects -----------------------
    tabItem(tabName = "selectEffects",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/08_SelectiveReportingEffects.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("selectEffPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("selectEffPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("selectEffPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("selectEffFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("selectEffFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("selectEffPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("selectEffPlot5")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsSelectEff", label = "Number of observations", value = 30, min = 10, max = 1000),
                                numericInput("nivSelectEff", label = "Number of independent variables", value = 3, min = 2, max = 10),
                                sliderInput("rivSelectEff", label = "Correlation of independent variables", value = 0.5, min = 0, max = 0.99, step = 0.01),
                                radioButtons("interactSelectEff", label = "Include Interactions", choiceNames = list("No", "Yes"), choiceValues = list("No", "Yes")),
                                radioButtons("strategySelectEff", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaSelectEff", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterSelectEff", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcSelectEff", "Start simulation"))))),

    # ------------------- Selective Reporting DV -------------------------------
    tabItem(tabName = "selectiveReportingDV",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/09_SelectiveReportingDV.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("SRDVPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("SRDVPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("SRDVPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("SRDVFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("SRDVFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("SRDVPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("SRDVPlot5"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("SRDVPlot6")),
                                     box(width=6, status = "primary",
                                         plotOutput("SRDVPlot7")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsSRDV", label = "Number of observations", value = 30, min = 10, max = 1000),
                                numericInput("nvarSRDV", label = "Number of dependent variables", value = 5, min = 1, max = 100),
                                sliderInput("rSRDV", label = "Correlation of dependent variables", value = 0.5, min = 0, max = 0.99, step = 0.01),
                                radioButtons("altSRDV", label = "Direction of the test", choiceNames = list("Two-sided", "One-sided (greater)"), choiceValues = list("two.sided", "greater")),
                                radioButtons("strategySRDV", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaSRDV", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterSRDV", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcSRDV", "Start simulation"))))),

    # ------------------- Selective Reporting IV -------------------------------
    tabItem(tabName = "selectiveReportingIV",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/10_SelectiveReportingIV.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("SRIVPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("SRIVPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("SRIVPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("SRIVFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("SRIVFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("SRIVPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("SRIVPlot5"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("SRIVPlot6")),
                                     box(width=6, status = "primary",
                                         plotOutput("SRIVPlot7")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsSRIV", label = "Number of observations", value = 30, min = 10, max = 1000),
                                numericInput("nvarSRIV", label = "Number of independent variables", value = 5, min = 1, max = 100),
                                sliderInput("rSRIV", label = "Correlation of independent variables", value = 0.5, min = 0, max = 0.99, step = 0.01),
                                radioButtons("altSRIV", label = "Direction of the test", choiceNames = list("Two-sided", "One-sided (greater)"), choiceValues = list("two.sided", "greater")),
                                radioButtons("strategySRIV", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaSRIV", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterSRIV", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcSRIV", "Start simulation"))))),

    # -------------- Exploiting Statistical Analysis Options ------------------
    tabItem(tabName = "statAnalysis",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/11_StatAnalysis.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("statAnalysisPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("statAnalysisPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("statAnalysisPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("statAnalysisFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("statAnalysisFPOrig")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsStatAnalysis", label = "Number of observations", value = 30, min = 10, max = 1000),
                                radioButtons("altStatAnalysis", label = "Direction of the test", choiceNames = list("Two-sided", "One-sided (greater)"), choiceValues = list("two.sided", "greater")),
                                radioButtons("strategyStatAnalysis", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaStatAnalysis", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterStatAnalysis", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcStatAnalysis", "Start simulation"))))),

    # -------------- Subgroup Analyses / Inclusion Criteria --------------------
    tabItem(tabName = "subgroupAnalysis",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/12_SubgroupAnalysis.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("subgroupPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("subgroupPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("subgroupPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("subgroupFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("subgroupFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("subgroupPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("subgroupPlot5"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("subgroupPlot6")),
                                     box(width=6, status = "primary",
                                         plotOutput("subgroupPlot7")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsSubgroup", label = "Number of observations", value = 30, min = 10, max = 1000),
                                numericInput("nsubvarsSubgroup", label = "Number of subgroup variables", value = 5, min = 1, max = 100),
                                radioButtons("altSubgroup", label = "Direction of the test", choiceNames = list("Two-sided", "One-sided (greater)"), choiceValues = list("two.sided", "greater")),
                                radioButtons("strategySubgroup", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaSubgroup", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterSubgroup", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcSubgroup", "Start simulation"))))),

    # ------------------ Variable Transformation -------------------------------
    tabItem(tabName = "variableTransformation",
            fluidRow(box(width = 12, status = "primary",
                         includeMarkdown("mddoc/13_VariableTransformation.md")
            )),
            fluidRow(column(width=8,
                            fixedRow(box(width=6, status="primary",
                                         plotOutput("varTransPlot1")),
                                     box(width=6, status="primary",
                                         plotOutput("varTransPlot2"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("varTransPlot3")),
                                     box(width=6, status = "primary",
                                         h4("False positive rate (p-hacked)"),
                                         textOutput("varTransFPHack"),
                                         h4("False positive rate (original)"),
                                         textOutput("varTransFPOrig"))),
                            fixedRow(box(width=6, status = "primary",
                                         plotOutput("varTransPlot4")),
                                     box(width=6, status = "primary",
                                         plotOutput("varTransPlot5")))),
                     column(width=4,
                            box(width=12, status="primary", height=800, background="navy",
                                h4("Simulation settings"),
                                numericInput("nobsVarTrans", label = "Number of observations", value = 30, min = 10, max = 1000),
                                radioButtons("transvarVarTrans", label = "Which variables should be transformed?", choiceNames = list("Predictors", "Outcomes", "Predictors and Outcomes"), choiceValues = list("x", "y", "xy")),
                                radioButtons("strategyVarTrans", label = "p-value selection method", choiceNames = list("First significant", "Smallest", "Smallest significant"), choiceValues = list("firstsig", "smallest", "smallest.sig")),
                                numericInput("alphaVarTrans", label = "Significance level", value = 0.05, min = 0.001, max = 0.2),
                                numericInput("iterVarTrans", label = "Simulation iterations", value = 1000, min = 10, max = 10000),
                                actionButton("calcVarTrans", "Start simulation")))))
  )
)


# ==============================================================================
# Create UI
# ==============================================================================
dashboardPage(header, sidebar, body)
